README.md

Add Aicas and Greenhills

---

README.md

A company built on developing SQL compilers and supporting technology.

Added CompilerWorks

---

README.md

Hi Matt! Hope everything you are doing alright!

Updating Theobroma's careers website

---

README.md

Thanks for maintaining this list and for the advice you gave me last year @mgaudet.
Since my search has finally come to an end, I figured I'd add some of the more interesting companies that I found along the way. Let me know if you'd like me to trim them down a bit (quite a few of them are "machine learning compiler" type companies).

Add some of the companies that I've learned about

---

README.md

Correct spelling of Ithaca

---

README.md

Added a position in Columbia using PL techniques for probabilistic inference

added Columbia position

---

README.md

Added TetraMem

---

README.md

Hi! I work at YoYo. We maintain compilers and are currently hiring, so I added us to the list.

Added YoYo Games to list

---

README.md

Add companies for APLs and Wolfram Research

---

README.md

Add DFINITY

---

README.md

Found it as a career opportunity

Add Nomic Labs

---

README.md

A few companies working on static analysis tooling + Crowdstrike with a DSL for their threat detection platform

Add Sonatype, Praetorian, TrustInSoft and Crowdstrike

---

README.md

I don't know much about them, but I found a bunch of offers that looked like they belong here:
https://www.imaginationtech.com/careers/vacancies/?job=501718
https://www.imaginationtech.com/careers/vacancies/?job=501616
https://www.imaginationtech.com/careers/vacancies/?job=501587

Add Imagination Technologies

---

README.md

Sambanova is a leading AI processor startup building the first-ever enterprise-grade CGRA dataflow system. Funding-wise, Sambanova is the best-funded AI company on the planet with over 1 Billion dollars raised. If you are a believer in dataflow programming, we want to work with you and build something cool together!
Caveat: seems my VSCode is cleaning up the tailing empty space, hope that is not bothering people too much for the PR review.

[SN] add Sambanova to the company list

---

README.md

Job Posting: https://boards.eu.greenhouse.io/nethermind/jobs/4034249101
Company website: https://nethermind.io

Add Nethermind

---

README.md

Based on https://jobs.bytedance.com/en/position/7121856641121044744/detail

Add ByteDance to README

---

README.md

Hi there! 
We'd like to add Xanadu to your list. We have a team working on compilation in the quantum computing space and will be hiring for several roles in future

Add Xanadu

---

README.md

Hi, Matthew!
Would you mind adding Distributive to your list?
Wes

add Distributive

---

README.md

Via https://x.com/_eseidel/status/1745507338583466042?s=20

Add Shorebird

---

README.md

Please add our company MicroDoc to the list.

Add MicroDoc

---

README.md

Reservoir Labs has been acquired by Qualcomm.

Reservoir Labs: strip

---

README.md

Nod.ai has been acquired by AMD.

Nod: strip

---

README.md

I work on upstream LLVM at Codasip :)

Codasip: add new company

---

README.md

OCaml Labs has joined Tarides.

OCaml Labs: strip

---

README.md

I just remembered that there are a few interns employed here.

Codasip: add internship tag

---

README.md

>I generally want evidence that a company has hired at some point in the past or will in the future (which excludes some boutique firms & early stage startups).
My team at Splunk is currently hiring https://jobs.jobvite.com/careers/splunk-careers/job/ovSjvfwV

Add Splunk

---

README.md

We are actively hiring for compiler engineers @ SEMRON, see https://semron.jobs.personio.de/

Add SEMRON

---

README.md

This accomplishes #188 and #187.

Remove Untether and Add Persimmons

---

README.md

The link also redirects to Qualcomm's site.

Nuvia: acquired by QComm; strip

---

README.md

It's been shuttered by the majority stakeholder, GM.

Cruise: strip

---

README.md

A member of the community, Simon Pilgrim, works from London, although it's unclear where the office is.

Sony: add compiler positions in UK

---

README.md

Ref: https://ambarella.wd108.myworkdayjobs.com/en-US/Ambarella/job/Computer-Vision-Compiler-engineer_JR100022.

Ambarella: add Taiwan location
